export const QUOTE_CREATE_REQUEST = 'QUOTE_CREATE_REQUEST';
export const QUOTE_CREATE_SUCCESS = 'QUOTE_CREATE_SUCCESS';
export const QUOTE_CREATE_FAIL = 'QUOTE_CREATE_FAIL';
export const QUOTE_CREATE_RESET = 'QUOTE_CREATE_RESET';
